### ISSUE TITLE
如果方便的话 ，可以给所有漫画加入一个 连载状态，例如 连载中 已完结  谢谢

### ISSUE THREAD

**Issue by lossme** [lossme/ComicBook#24]
如果方便的话 ，可以给所有漫画加入一个 连载状态，例如 连载中 已完结  谢谢

_Originally posted by @8108905 in https://github.com/lossme/TencentComicBook/issue_comments/708167968_

**Comment by lossme** [comment]
有时间再搞下，感觉可以弄些标签来搜索

**Comment by 8108905** [comment]
谢谢 ！请问 http://127.0.0.1:8000/api/manhuagui/comic/19430/1  这个修复了吗？ 谢谢

**Comment by lossme** [comment]
已经修复了的，更新下代码看看

**Comment by 8108905** [comment]
的确修复 谢谢你！希望检查一下   manhuagui  1128 是航海王 章节不太全  

http://127.0.0.1:8000/api/manhuagui/comic/1128

**Comment by lossme** [comment]
有单行本跟番外篇这种格式，好像不太兼容，需要额外加字段才能处理。

**Comment by 8108905** [comment]
的确是不好弄啊 ！

**Comment by lossme** [comment]
https://www.manhuagui.com/comic/1128/
加上了 番外篇和单行本

**Comment by 8108905** [comment]
谢谢了！ 有时间可以看下！ https://www.manhuatai.com/  谢谢

**Comment by lossme** [comment]
> 谢谢了！ 有时间可以看下！ https://www.manhuatai.com/ 谢谢
加上了

**Comment by 8108905** [comment]
老大 太惊喜了 ，根据tag搜索 manhuagui 好像无效！

**Comment by 8108905** [comment]
http://127.0.0.1:8000/api/manhuagui/tags
获取到manhuagui的连载参数是 ‘6_lianzai’ 

http://127.0.0.1:8000/api/manhuagui/list?tag=6_lianzai&page=1
提示500错误

**Comment by lossme** [comment]
已修复

**Comment by 8108905** [comment]
谢谢你！ 这么及时修复了！其实 manhuatai manhuagui dm5 这三个网站 几乎把 国漫日漫韩漫 都采集了 ，无论腾讯 有妖气等其他 收费还是免费！韩漫18comic 绅士漫画 ，也够了，这五个漫画网站采集了 ，无需在浪费时间在其他漫画上！

http://127.0.0.1:8000//api/manhuagui/list?tag=6_lianzai&page=1 （前十部漫画有图片，后面’ cover_image_url‘:null）;
原站：https://www.manhuagui.com/list/lianzai/ 都有图片，希望检查下 谢谢！

**Comment by lossme** [comment]
已修复

**Comment by 8108905** [comment]
最后一个问题 ：http://127.0.0.1:8000/api/manhuagui/comic/30662  可以在这个api 里面返回个 地区字段吗？谢谢

**Comment by 8108905** [comment]
http://127.0.0.1:8000/api/manhuagui/list?tag=6_lianzai,1_china&page=1 请问下可以返回当前参数的总页数吗？ 谢谢

**Comment by lossme** [comment]
1. 总页数可以不用吧，一直往后翻页直到返回空就不继续翻页了
2. 地区感觉不是很重要

**Comment by lossme** [comment]
是需要带上地区标签（可用于搜索的），不仅仅是文本信息？

**Comment by 8108905** [comment]
嗯 page=9999999应该是也是显示最后一页的内容！希望看一下哈。谢谢！

**Comment by lossme** [comment]
https://www.manhuagui.com/list/index_p906.html
https://www.manhuagui.com/list/index_p9999.html
源站也是这样的

**Comment by 8108905** [comment]
嗯 其实都可以克服 谢谢！ 暂时没什么问题了！

**Comment by lossme** [comment]
不想改而已，哈哈哈

**Comment by 8108905** [comment]
centos 7 ; 使用下面命令安装
`yum install centos-release-scl
yum install rh-python38
scl enable rh-python38 bash
python --version Python 3.8.0.

安装最新版 [pip](url)
pip install --upgrade pip`

-------------------------------
`[root@LavishCourteous-VM TencentComicBook]# python -m pip install -r requirements-api.txt
Requirement already satisfied: Pillow>=6.2.0 in /opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages (from -r requirements-api.txt (line 1)) (8.0.1)
Requirement already satisfied: requests>=2.20.0 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from -r requirements-api.txt (line 2)) (2.24.0)
Requirement already satisfied: PyExecJS>=1.5.1 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from -r requirements-api.txt (line 4)) (1.5.1)
Requirement already satisfied: bs4>=0.0.1 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from -r requirements-api.txt (line 5)) (0.0.1)
Requirement already satisfied: img2pdf>=0.4.0 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from -r requirements-api.txt (line 6)) (0.4.0)
Requirement already satisfied: gunicorn>=20.0.4 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from -r requirements-api.txt (line 8)) (20.0.4)
Requirement already satisfied: Flask>=1.1.1 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from -r requirements-api.txt (line 9)) (1.1.2)
Requirement already satisfied: Flask-Script>=2.0.6 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from -r requirements-api.txt (line 10)) (2.0.6)
Requirement already satisfied: Flask-SQLAlchemy>=2.4.4 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from -r requirements-api.txt (line 11)) (2.4.4)
Requirement already satisfied: cachetools>=4.1.1 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from -r requirements-api.txt (line 12)) (4.1.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from requests>=2.20.0->-r requirements-api.txt (line 2)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from requests>=2.20.0->-r requirements-api.txt (line 2)) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from requests>=2.20.0->-r requirements-api.txt (line 2)) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from requests>=2.20.0->-r requirements-api.txt (line 2)) (2.10)
Requirement already satisfied: six>=1.10.0 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from PyExecJS>=1.5.1->-r requirements-api.txt (line 4)) (1.15.0)
Requirement already satisfied: beautifulsoup4 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from bs4>=0.0.1->-r requirements-api.txt (line 5)) (4.9.3)
Requirement already satisfied: pikepdf in /opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages (from img2pdf>=0.4.0->-r requirements-api.txt (line 6)) (1.19.3)
Requirement already satisfied: setuptools>=3.0 in /opt/rh/rh-python38/root/usr/lib/python3.8/site-packages (from gunicorn>=20.0.4->-r requirements-api.txt (line 8)) (41.6.0)
Requirement already satisfied: Werkzeug>=0.15 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from Flask>=1.1.1->-r requirements-api.txt (line 9)) (1.0.1)
Requirement already satisfied: Jinja2>=2.10.1 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from Flask>=1.1.1->-r requirements-api.txt (line 9)) (2.11.2)
Requirement already satisfied: itsdangerous>=0.24 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from Flask>=1.1.1->-r requirements-api.txt (line 9)) (1.1.0)
Requirement already satisfied: click>=5.1 in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from Flask>=1.1.1->-r requirements-api.txt (line 9)) (7.1.2)
Requirement already satisfied: SQLAlchemy>=0.8.0 in /opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages (from Flask-SQLAlchemy>=2.4.4->-r requirements-api.txt (line 11)) (1.3.20)
Requirement already satisfied: soupsieve>1.2; python_version >= "3.0" in /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages (from beautifulsoup4->bs4>=0.0.1->-r requirements-api.txt (line 5)) (2.0.1)
Requirement already satisfied: lxml>=4.0 in /opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages (from pikepdf->img2pdf>=0.4.0->-r requirements-api.txt (line 6)) (4.6.1)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages (from Jinja2>=2.10.1->Flask>=1.1.1->-r requirements-api.txt (line 9)) (1.1.1)
[root@LavishCourteous-VM TencentComicBook]# 
`
`# 2.2 创建新数据库 报错
python manage.py createdb`
`
[root@LavishCourteous-VM TencentComicBook]# python manage.py createdb
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'api.config.Config')
  File "/root/TencentComicBook/api/__init__.py", line 27, in create_app
    from .views import (
  File "/root/TencentComicBook/api/views.py", line 15, in <module>
    from . import task
  File "/root/TencentComicBook/api/task.py", line 10, in <module>
    from .model import (
  File "/root/TencentComicBook/api/model.py", line 1, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'
`
请问下您知道什么原因吗？ 插件也安装成功了~ 本地mac电脑没问题！

**Comment by lossme** [comment]
先安装下这个依赖 pip install pytz

**Comment by 8108905** [comment]
完美搞定！采集漫画柜 好像ip被封了，获取不到了，我的采集速度很慢！有没办法设置代理ip

**Comment by 8108905** [comment]
跟您道个歉 ！ 我之前提出的manhuatai 漫画，以及kuaikanmanhua 他们里面并非没有免费收费分类，所以收费获取不到图片地址～而且大部分都需要 手机观看～其实可以把他删掉了

**Comment by 8108905** [comment]
http://127.0.0.1:8000/api/wnacg/comic/108438
http://www.wnacg.org/photos-index-aid-108438.html
绅士漫画标签不全！  其实每部漫画都有分类的～如果方便的话 ～！！！！我只使用api如果有分类的话 会更灵活 ！

**Comment by 8108905** [comment]
http://127.0.0.1:8000/api/qq/comic/511915
https://ac.qq.com/Comic/comicInfo/id/511915
没有标签 希望查看下

**Comment by 8108905** [comment]
https://www.u17.com/comic/191543.html

http://127.0.0.1:8000/api/u17/comic/191543 这个没有标签

**Comment by 8108905** [comment]
API经过测试采集集漫画柜 即使速度很慢 大约采集10部漫画左右，会被封ip ;大约要等待24小时后才可以被解封 ,请问下有办法设置代理ip吗？谢谢

**Comment by lossme** [comment]
> API经过测试采集集漫画柜 即使速度很慢 大约采集10部漫画左右，会被封ip ;大约要等待24小时后才可以被解封 ,请问下有办法设置代理ip吗？谢谢

不支持这种采集行为
