### ISSUE TITLE
腾讯成功了，快看却失败了

### ISSUE THREAD

**Issue by Oldsport-996** [lossme/ComicBook#28]
![失败](https://user-images.githubusercontent.com/66009263/99866613-7bd91580-2bed-11eb-841a-4296c320633a.png)

python -m onepiece --site=kuaikan --comicid=4319 --chapter=1 --login --driver-path "G:\0：临时下载中转站\111\chromedriver.exe" --driver-type="Chrome"                
上面这个是我的运行代码，下载腾讯成功了，快看漫画却失败了；请教一下大佬解决
没有代码基础，不太看得懂是什么问题出错了
Traceback (most recent call last):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 262: illegal multibyte sequence
IndexError: list index out of range

**Comment by Oldsport-996** [comment]
登录应该也没问题，显示login success； 漫画我测试下的是快看编号4319，我独自升级，第一话免费章节

**Comment by lossme** [comment]
看不出眉头，可能是网络问题，我这边重现不了你说的问题
