### ISSUE TITLE
可以留下个联系方式吗？想请你写个爬虫！

### ISSUE THREAD

**Issue by 8108905** [lossme/ComicBook#38]

**Comment by lossme** [comment]
能力跟时间都有限，搞不了什么大项目哈。有需求可以在这提

**Comment by 8108905** [comment]
比漫画简单 ，一个手机号码列表网站；最终效果类似漫画 url+参数 获得json数据 即可；

**Comment by 8108905** [comment]
https://www.numberbarn.com/search?search=&category=XYYY 
https://www.numberbarn.com/search?search=&category=XYYY&city=Anderson,%20IN&sort=price%2B&priceRange=50,99
最终效果类似漫画api 即可，json数据 只要返回 号码 价格 地区 就好；

**Comment by 8108905** [comment]
怎么样 有兴趣吗  谢谢

**Comment by lossme** [comment]
这个搞不来
