### ISSUE TITLE
希望可以爬取biliplus

### ISSUE THREAD

**Issue by fjjking** [lossme/ComicBook#42]
biliplus可以观看到部分BILIBILI付费漫画
希望可以提供爬取

**Comment by lossme** [comment]
biliplus 这个站点哪里有漫画看，付费漫画建议还是先购买。

**Comment by fjjking** [comment]
`https://www.biliplus.com/manga/?act=detail&mangaid=28565`
（想看的太多了XD）

**Comment by lossme** [comment]
这个源不打算添加
