### ISSUE TITLE
KeyError: 'driver_path'

### ISSUE THREAD

**Issue by gulup** [lossme/ComicBook#44]
更新0.3.14之后，任何操作都会报这个错：
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\lib\site-packages\onepiece\__main__.py", line 4, in <module>
    main()
  File "C:\Python38\lib\site-packages\onepiece\cli.py", line 305, in main
    CrawlerBase.DRIVER_PATH = config.driver_path
  File "C:\Python38\lib\site-packages\onepiece\config.py", line 102, in driver_path
    return self.config[self.DRIVER_PATH]
KeyError: 'driver_path'

**Comment by lossme** [comment]
更新试下

**Comment by gulup** [comment]
Requirement already satisfied: Pillow>=6.2.0 in c:\python38\lib\site-packages (from onepiece==0.3.14) (7.2.0)
Requirement already satisfied: requests in c:\python38\lib\site-packages (from onepiece==0.3.14) (2.23.0)
Requirement already satisfied: PyExecJS in c:\python38\lib\site-packages (from onepiece==0.3.14) (1.5.1)
Requirement already satisfied: bs4 in c:\python38\lib\site-packages (from onepiece==0.3.14) (0.0.1)
Requirement already satisfied: jsbeautifier in c:\python38\lib\site-packages (from onepiece==0.3.14) (1.13.0)
Requirement already satisfied: lzstring in c:\python38\lib\site-packages (from onepiece==0.3.14) (1.0.4)
Requirement already satisfied: dukpy in c:\python38\lib\site-packages (from onepiece==0.3.14) (0.2.3)
Requirement already satisfied: beautifulsoup4 in c:\python38\lib\site-packages (from bs4->onepiece==0.3.14) (4.9.3)
Requirement already satisfied: soupsieve>1.2 in c:\python38\lib\site-packages (from beautifulsoup4->bs4->onepiece==0.3.14) (2.1)
Requirement already satisfied: six>=1.13.0 in c:\python38\lib\site-packages (from jsbeautifier->onepiece==0.3.14) (1.15.0)
Requirement already satisfied: editorconfig>=0.12.2 in c:\python38\lib\site-packages (from jsbeautifier->onepiece==0.3.14) (0.12.2)
Requirement already satisfied: future>=0.14.0 in c:\python38\lib\site-packages (from lzstring->onepiece==0.3.14) (0.18.2)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\python38\lib\site-packages (from requests->onepiece==0.3.14) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\python38\lib\site-packages (from requests->onepiece==0.3.14) (1.25.8)
Requirement already satisfied: idna<3,>=2.5 in c:\python38\lib\site-packages (from requests->onepiece==0.3.14) (2.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\python38\lib\site-packages (from requests->onepiece==0.3.14) (2020.4.5.1)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\python38\lib\site-packages (from requests->onepiece==0.3.14) (1.7.1)

更新了，还是一样的报错

**Comment by lossme** [comment]
你是用哪种安装方式的呢

**Comment by gulup** [comment]
> 你是用哪种安装方式的呢

cmd在线安装

**Comment by lossme** [comment]
```
pip3 uninstall onepiece
pip3 install -U git+https://github.com/lossme/ComicBook
```
卸载重装呢

**Comment by gulup** [comment]
> ```
> pip3 uninstall onepiece
> pip3 install -U git+https://github.com/lossme/ComicBook
> ```
> 
> 卸载重装呢

解决了
