### ISSUE TITLE
DM5查询缺失

### ISSUE THREAD

**Issue by gulup** [lossme/ComicBook#45]
DM5查询漫画内容会有缺失。例如查询机器猫：
![image](https://user-images.githubusercontent.com/3413433/103266447-91aad900-49ea-11eb-870e-fa98ff90da4a.png)
实际上的机器猫没有被查出来：
https://www.dm5.com/manhua-jiqimao/

**Comment by lossme** [comment]
应该把第一个搜索结果也添加进来，迟点我再修复这个问题
![image](https://user-images.githubusercontent.com/12013826/103267458-83f65300-49ec-11eb-8c08-4dbfa4be8acc.png)
