### ISSUE TITLE
DM5下载失效

### ISSUE THREAD

**Issue by gulup** [lossme/ComicBook#46]
![image](https://user-images.githubusercontent.com/3413433/103266578-ddf61900-49ea-11eb-8f40-d06a54fd524c.png)
2020/12/29 15:30:44 onepiece.image 122 [WARNING] image download error. error=img download error: url=https://manhua1018-61-174-50-98.cdndm5.com/d/哆啦A梦PLUS/哆 啦A梦PLUS_VOL01/doraemonplus01_005.jpg?cid=76177&key=c06f6fdc9fd1feafe0055bd0b01ce840 error: img download error: url=https://manhua1018-61-174-50-98.cdndm5.com/d/哆啦A梦PLUS/哆啦A梦PLUS_VOL01/doraemonplus01_005.jpg?cid=76177&key=c06f6fdc9fd1feafe0055bd0b01ce840 status_code=404

**Comment by lossme** [comment]
更新代码试下？我这边并未出现这个异常
