### ISSUE TITLE
可能因为扒去速度过快导致被漫画柜封禁IP

### ISSUE THREAD

**Issue by fjjking** [lossme/ComicBook#47]
希望可以增加一点延迟，或者自定义延迟的参数
现在每扒取20~30章漫画柜就会拒绝连接

**Comment by lossme** [comment]
更新之后 参数里添加`--crawler-delay=10` 试试

**Comment by fjjking** [comment]
非常感谢，另外经过测试15s比较安全，10s还是容易被封
