### ISSUE TITLE
部分漫画章节标题带有特殊符号导致下载出错

### ISSUE THREAD

**Issue by YIQMaster** [lossme/ComicBook#49]
操作系统：windows 10
运行代码：python -m onepiece --site=qq --comicid=631246 --chapter=1-20
报错信息：onepiece.image 120 [WARNING] image download error. error=[Errno 2] No such file or directory: 'download\\腾讯漫画\\史上第一掌门\\014 不针对你，我是说在座的各位...\\1.jpg'等

**Comment by lossme** [comment]
好像是windows文件夹不能包含`.`

**Comment by YIQMaster** [comment]
是的，除此之外还有别的特殊字符，文件名称中不能包含 \ / : * ? " < > | 一共9个特殊字符，在保存前能过滤特殊字符再保存吗？

**Comment by lossme** [comment]
> 是的，除此之外还有别的特殊字符，文件名称中不能包含 \ / : * ? " < > | 一共9个特殊字符，在保存前能过滤特殊字符再保存吗？

这些已经处理了

**Comment by YIQMaster** [comment]
我见到生成的文件夹过滤了特殊字符，但是下载图片的保存路径没有过滤呢，依然是报错
