### ISSUE TITLE
漫画柜报错

### ISSUE THREAD

**Issue by animfanis123** [lossme/ComicBook#50]
python3 -m onepiece --site=manhuagui --comicid=8180 --chapter=1

onepiece.exceptions.ChapterNotFound: source not found. site=manhuagui comicid=8180 chapter_number=1 source_url=https://www.manhuagui.com/comic/8180

**Comment by lossme** [comment]
![image](https://user-images.githubusercontent.com/12013826/103777597-17bec380-506c-11eb-9cc3-01d24f4ff599.png)
默认下载的是单话，单行本要这样下载
```sh
python3 -m onepiece --site=manhuagui --comicid=8180 --chapter=1 --ext-name=单行本
```

**Comment by lossme** [comment]
因为漫画柜有 单话、单行本、番外篇 这些。目前是自动选择单话 作为默认的章节列表。
可以这样下载单行本
```sh
python3 -m onepiece --site=manhuagui --comicid=8180 --chapter=1 --ext-name 单行本
```


或者更新下代码，代码做了处理。如果只有一种（单话、单行本、番外篇等）就下载这种类别下的漫画内容，不用额外指定 `--ext-name`参数
```sh
python3 -m onepiece --site=manhuagui --comicid=8180 --chapter=1
```

**Comment by animfanis123** [comment]
谢谢，又仔细拜读了您的代码，谢谢您的工作。
