### ISSUE TITLE
请问一下,其他站点的命令应该怎么使用呢?

### ISSUE THREAD

**Issue by nqianaaron** [lossme/ComicBook#53]
另外尝试了很久python3 -m onepiece --site=qq --comicid=542330 --all命令一直不好用.后来改成python -m onepiece --site=qq --comicid=542330 --all 把3删除就好了.
感谢大佬分享的这么好的开源项目.

**Comment by lossme** [comment]
可以从[已支持的站点](https://github.com/lossme/ComicBook/projects/1)
找到想要下载的漫画的章节列表页面的URL，然后再搭配其它参数来下载
```sh
python3 -m onepiece --url="https://manga.bilibili.com/detail/mc28603" --chapter=1
```
