### ISSUE TITLE
部分漫画标题的特殊符号导致下载文件无法保存

### ISSUE THREAD

**Issue by northtowertop** [lossme/ComicBook#56]
如题，刚刚在bilibili碰到一个， 是本漫画的第41话，名字叫 Little little......
https://manga.bilibili.com/m/detail/mc28085
使用onepiece生成的文件夹叫Little little，会自动cut掉后面的 ...... 导致无法读取到对应的文件夹内。
报错如下：
2021/01/13 17:28:35 onepiece.cli 162 [INFO] 正在下载 【愚蠢天使与恶魔共舞】 43 【Little little......】
2021/01/13 17:28:39 onepiece.image 119 [WARNING] image download error. error=[Errno 2] No such file or directory: 'download\\哔哩哔哩漫画\\愚蠢天使与恶魔共舞\\043 Little little......\\1.jpg'
2021/01/13 17:28:39 onepiece.image 119 [WARNING] image download error. error=[Errno 2] No such file or directory: 'download\\哔哩哔哩漫画\\愚蠢天使与恶魔共舞\\043 Little little......\\2.jpg'

**Comment by lossme** [comment]
麻烦更新代码再试试
