### ISSUE TITLE
KeyError: 'data'

### ISSUE THREAD

**Issue by premnh** [lossme/ComicBook#61]
File "H:\pip\lib\site-packages\onepiece\site\bilibili.py", line 104, in get_comicbook_item
    name = api_data['data']['title']
KeyError: 'data'

![0B`$XRDR3TH}`OAQ{%(004Y](https://user-images.githubusercontent.com/78066059/105944234-df743900-609d-11eb-9977-9ffb49f11059.png)

**Comment by lossme** [comment]
1. 需要更新下代码版本
2. 默认下载最新一话，这漫画最新一话是付费资源，需要导出已付费账号的cookies，然后命令指定cookies的路径来下载

**Comment by premnh** [comment]
python -m onepiece -s bilibili -id mc27166 -c 36 --cookies-path="0.json"
2021/01/27 15:01:44 onepiece.worker 19 [INFO] set worker. worker=4
2021/01/27 15:01:44 onepiece.cli 309 [INFO] 哔哩哔哩漫画 【怪物事变】 更新至: 051 【使命】 数据来源: https://manga.bilibili.com/m/detail/mc27166
2021/01/27 15:02:47 onepiece.cli 190 [ERROR] download comicbook error. site=bilibili comicid=27166 chapter_number=36
Traceback (most recent call last):
  File "H:\pip\lib\site-packages\onepiece\cli.py", line 167, in download_main
    chapter = comicbook.Chapter(chapter_number, ext_name=ext_name)
  File "H:\pip\lib\site-packages\onepiece\comicbook.py", line 143, in Chapter
    chapter_item = self.crawler.get_chapter_item(citem)
  File "H:\pip\lib\site-packages\onepiece\site\bilibili.py", line 132, in get_chapter_item
    chapter_api_data = self.get_chapter_api_data(cid=citem.cid)
  File "H:\pip\lib\site-packages\onepiece\site\bilibili.py", line 84, in get_chapter_api_data
    raise ChapterNotFound(f"Please read on bilibili Manga APP. {source_url}")
onepiece.exceptions.ChapterNotFound: Please read on bilibili Manga APP. https://manga.bilibili.com/mc27166/371904

请问出现这个是什么原因呢 代码已更新 cookie已导出

![LXF_JJJG9~`CI8F6RXIQHUO](https://user-images.githubusercontent.com/78066059/105955357-1d2e8d00-60b1-11eb-9611-2613f615f8c4.png)

**Comment by lossme** [comment]
漫画购买了没，你的账号能不能看这个付费章节

**Comment by premnh** [comment]
你好 是已经付费过了的 但是还是不行 请问可能是cookie的问题吗?

**Comment by lossme** [comment]
可能是
