### ISSUE TITLE
哔哩哔哩漫画下载某一特定章节出错

### ISSUE THREAD

**Issue by jiu-xiao-233** [lossme/ComicBook#62]
TencentComicBook\onepiece\image.py:126: UserWarning: [Errno 2] No such file or directory
并提示warnings.warn(str(e))

**Comment by lossme** [comment]
看起来是很久远的版本的问题，更新后再试试？

**Comment by jiu-xiao-233** [comment]
啊，果然是，已解决
十分感谢
